### ISSUE TITLE
Use of GPL license

### ISSUE THREAD

**Issue by edmundmunday** [jekuer/add-to-calendar-button#10]
Hi there, was the choice of GPL licensing intentional? GPL license makes it effectively impossible for anyone to use this for a commercial project.

Seems like you've put a HUGE amount of work on this, I just don't want that to be wasted because of a restrictive license that means people won't see your awesome work.

**Comment by jekuer** [comment]
@edmundmunday , GPL was used on purpose.
You CAN use it in commercial projects - as long as it is no essential part of it (because the GPL will then require you to publish and distribute the software also under GPL.
Check the top section (the one, generated by GitHub) at https://github.com/jekuer/add-to-calendar-button/blob/main/LICENSE.txt for all limitations and conditions.

Example 1: Use the button on your corporate website: Allowed (but keep the copyright information in the source code).
Example 2: Building a tool to generate event buttons and sell it: Difficult.

But to keep it easy, you can describe your project (and how you want to use the button) to me, and I can tell you the implications.

**Comment by edmundmunday** [comment]
![image](https://user-images.githubusercontent.com/20222644/144017924-77220c9b-b564-4e92-8375-4ef21b53e4df.png)

The GPL is extremely vague and puts people at extremely serious risk, Github's summary definitely isn't safe "legal advice" and they say the same.

As a general rule, nobody building a commercial product is going to allow a GPL licensed piece of code into their product, the risk is simply too high.

For example, we are building a product that allows people to book community spaces that their county/city council makes available. We charge the city councils to use the tool as a SaaS product, we'd love to implement your button as a quick way for people to download the details of their booking as a calendar invite.

Just to be clear, I'm not having a go at you for choosing the license, just sharing feedback. With the current license, we wouldn't be comfortable using it - it's too risky.

**Comment by jekuer** [comment]
@edmundmunday , what would be your next best solution in terms of licensing, wich keeps the open source character and makes safe that authors receive some credit (meaning at least to not remove any copyright notes), while also making sure that people do not start basically selling the work (which is thought to be free to user)?

**Comment by edmundmunday** [comment]
@jekuer - There are a few tools today implementing more permissive licenses such as MIT (with attribution, so people must acknowledge your work), and then appending what's called the "Commons Clause" addendum which effectively limits anyone using your tool from reselling **that tool**. This prevents someone from just relabelling your library and then trying to charge for it, but allows you to share it with the community as a component of larger applications if that's what your goal is with the library.

Info on Commons Clause can be found here: https://commonsclause.com/
Last time I checked, N8N.io was implementing the Apache 2.0 license with the Commons Clause addendum for exactly the situation you're talking about here.

**Comment by jekuer** [comment]
Thanks - I like this approach. Will check it out and most probably update the next days.

**Comment by jekuer** [comment]
@edmundmunday , updated the license with v1.3.0
Thanks a lot for your input.
