### ISSUE TITLE
Blank screen after sending outlook invite

### ISSUE THREAD

**Issue by bayu-kusumah** [jekuer/add-to-calendar-button#64]
I use office 365 with a blank screen after sending the event Calendar, what is the problem? I try your demo same blank screen too

help, please

**Comment by jekuer** [comment]
Can you please add more details?

Like when exactly do you experience the blank screen (at which step)? Is it a blank screen on the website with the button, or your outlook app (or desktop application), or the whole operating system? What does blank screen mean - white, black, ...?
Maybe it is just an empty new tab in the browser? which browser?

Thanks a lot in advance for your support!

**Comment by bayu-kusumah** [comment]
detail is:

new tab window showing form sending invite calendar and then after click button sending an invite

1. white screen on the website 
2. use the chrome browser

![sending_invite](https://user-images.githubusercontent.com/96506501/170900346-5d1cf446-2cc6-414f-bb0c-5d1287eb23d1.png)

**Comment by jekuer** [comment]
Thanks a lot.
Unfortunately, this is an issue by outlook, which we do not have any chance to change from our side.
While testing this a little bit deeper, it seemed like in some cases, the tab gets closed after "Send". In other cases, the blank screen appeared.
Since this is "only" a small visual glitch, which does not impact the actual functionality; and it is not in our hands here, I will close the issue.
