### ISSUE TITLE
Support line breaks for the description + mind different methods per calendar type

### ISSUE THREAD

**Issue by schietegal** [jekuer/add-to-calendar-button#7]
Title says it all.

Google Cal doesn't recognize \n as line break. `<br />` is needed for that. For now you can only line break on ical OR google Calendar, but not both. 

By the way: Thank you very much! The button helps a lot!

**Comment by jekuer** [comment]
Since line breaks are not supported at all at the moment, I see this as a feature request :)
I think we should add a function, which rewrites \n to <br /> for Google and the other way around <br /> to \n for ical.
This way, it is up to the user how he/she wants to define line breaks in the description.

Do you know how the situation looks like for the other calendar types?

**Comment by schietegal** [comment]
Not directly supported, but you can still /n (//n) to get a line break

Google and Outlook recognizes <br /> as line break, for the other vendors, i don't know.

**Comment by jekuer** [comment]
Tested it in depth:
- Google did recognize \n as line break on my side. They support both, \n and <br>.
- Outlook/M365 (web) also support both.
- Yahoo only goes with \n.
- While for the iCal \\n does the trick.

So, the solution will require to:
1. transform all <br>, <br/>, <br /> to \n.
2. and then all \n to \\n for the iCal.

This will enable you to use line breaks consistently over all calendar types.

**Comment by jekuer** [comment]
Done with 1.2.0
